### ISSUE TITLE
404 error on url atlas.hashicorp.com/ubuntu/xenial64

### ISSUE THREAD

**Issue by ranjanmanish** [equelin/vagrant-influxdb-grafana#3]
![image](https://user-images.githubusercontent.com/1888190/37926494-557b802a-30ec-11e8-87c6-c31b20a2ea68.png)

I cross verified on the actual site and same `404` error

**Comment by equelin** [comment]
Hello,

I need to test by myself but I've been able to find that box on the vagrant
cloud.

https://app.vagrantup.com/ubuntu/boxes/xenial64

Could you please test again with this simple Vagrantfile ?

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
end

**Comment by ranjanmanish** [comment]
Thanks for trying. It so turned out that once I upgraded to latest virtual box, I was able to install ubuntu xenial the provided Vagrant file.  I do not know what was my last virtual box version, but I can conform that it works on `Version 5.2.8 r121009 (Qt5.6.3)` .

**Comment by equelin** [comment]
Good to know !
